build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "OpenSSL/1.1.0i"
    CONAN_USERNAME: "rhard"
    CONAN_LOGIN_USERNAME: "rhard"
    CONAN_CHANNEL: "testing"
    CONAN_UPLOAD: "https://api.bintray.com/conan/rhard/conan"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    CONAN_TOTAL_PAGES: 2
    #CONAN_UPLOAD_ONLY_WHEN_STABLE: 1 # Will only upload when the branch matches "release/*"
    CONAN_BUILD_POLICY: "outdated"

    matrix:
        - MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix"
          CONAN_BUILD_REQUIRES: "msys2_installer/latest@bincrafters/stable"
          CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
          CONAN_CURRENT_PAGE: 1

        - MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix"
          CONAN_BUILD_REQUIRES: "msys2_installer/latest@bincrafters/stable"
          CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
          CONAN_CURRENT_PAGE: 2

        - MINGW_CONFIGURATIONS: "5@x86_64@seh@posix"
          CONAN_BUILD_REQUIRES: "msys2_installer/latest@bincrafters/stable"
          CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
          CONAN_CURRENT_PAGE: 1

        - MINGW_CONFIGURATIONS: "5@x86_64@seh@posix"
          CONAN_BUILD_REQUIRES: "msys2_installer/latest@bincrafters/stable"
          CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
          CONAN_CURRENT_PAGE: 2

        - MINGW_CONFIGURATIONS: "6@x86_64@seh@posix"
          CONAN_BUILD_REQUIRES: "msys2_installer/latest@bincrafters/stable"
          CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
          CONAN_CURRENT_PAGE: 1

        - MINGW_CONFIGURATIONS: "6@x86_64@seh@posix"
          CONAN_BUILD_REQUIRES: "msys2_installer/latest@bincrafters/stable"
          CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
          CONAN_CURRENT_PAGE: 2

        - MINGW_CONFIGURATIONS: "7@x86_64@seh@posix"
          CONAN_BUILD_REQUIRES: "msys2_installer/latest@bincrafters/stable"
          CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
          CONAN_CURRENT_PAGE: 1

        - MINGW_CONFIGURATIONS: "7@x86_64@seh@posix"
          CONAN_BUILD_REQUIRES: "msys2_installer/latest@bincrafters/stable"
          CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
          CONAN_CURRENT_PAGE: 2

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_CURRENT_PAGE: 2

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_CURRENT_PAGE: 2

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_CURRENT_PAGE: 2



install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
